use_frameworks!

platform :ios, '9.0'

target 'LKPlayerModule_Example' do
  pod 'LKPlayerModule', :path => '../'

  target 'LKPlayerModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
